=== d12y12/DevCenter/devspace/schema/project_only_schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "project_schema.json",
  "type": "object",
  "required": [
    "project",
    "version",
    "author",
    "project_dir",
    "host",
    "servers"
  ],
  "properties": {
    "project": {
      "type": "string",
      "minLength": 1,
      "maxLength": 10,
      "pattern": "^([a-zA-Z\\d](?:[a-zA-Z\\d]|-(?=[a-zA-Z\\d]))*)$"
    },
    "version": {
      "type": "string"
    },
    "author": {
      "type": "string"
    },
    "project_dir": {
      "type": "string"
    },
    "host": {
      "type": "string"
    },
    "servers": {
      "id": "#/properties/servers",
      "type": "object",
      "patternProperties": {
        "^([a-zA-Z\\d](?:[a-zA-Z\\d]|-(?=[a-zA-Z\\d])){0,9})$": {
          "$ref": "#/definitions/server"
        }
      },
      "additionalProperties": false
    }
  },
  "additionalProperties": false,
  "definitions": {
    "server": {
      "id": "#/definitions/server",
      "type": "object",
      "required": [
        "type",
        "port",
        "localization",
        "services"
      ],
      "properties": {
        "type": {
          "type": "string"
        },
        "port": {
          "type": "integer",
          "minimum": 8000,
          "maximum": 9000
        },
        "localization": {
          "type": "boolean"
        },
        "services": {
          "type": "object"
        }
      },
      "additionalProperties": false
    }
  }
}

=== d12y12/DevCenter/devspace/schema/project_example.json
{
  "project": "test",
  "version": "0.1.0",
  "author": "yang <d12y12@hotmail.com>",
  "project_dir": "E:/Git/DevSpace/workdir",
  "host": "192.168.0.108",
  "servers": {
    "demo": {
      "port": 8080,
      "type": "GitMirror",
      "localization": true,
      "services": {
        "yocto": {
          "cgit_options": {
            "title": "Mirror Repositories",
            "description": "",
            "max-repo-count": 50,
            "logo": {
              "light": "E:/Git/DevSpace/devspace/templates/example/yocto-logo-light.png",
              "dark": "E:/Git/DevSpace/devspace/templates/example/yocto-logo-dark.png"
            }
          },
          "synchronization": {
            "consistency": true,
            "crontab": "0 */1 * * *"
          },
          "repositories": {
            "cgit": [
              {
                "source": "http://git.yoctoproject.org/cgit.cgi/",
                "excludes": [
                  "http://git.yoctoproject.org/clean/cgit.cgi/yocto-testresults/",
                  "http://git.yoctoproject.org/clean/cgit.cgi/yp-qa-build-perf-data/"
                ],
                "targets": []
              }
            ],
            "github": []
          }
        },
        "github": {
          "cgit_options": {
            "title": "Mirror Repositories",
            "description": "",
            "max-repo-count": 50,
            "logo": {
              "light": "E:/Git/DevSpace/devspace/templates/example/github-logo-light.png",
              "dark": "E:/Git/DevSpace/devspace/templates/example/github-logo-dark.png"
            }
          },
          "synchronization": {
            "consistency": true,
            "crontab": "0 */1 * * *"
          },
          "repositories": {
            "cgit": [],
            "github": [
              {
                "source": "d12y12",
                "excludes": [],
                "targets": []
              },
              {
                "source": "scrapy/scrapy",
                "excludes": [],
                "targets": []
              }
            ]
          }
        }
      }
    }
  }
}
